#this is going to be the starting PY file for the Model portion of our code


#Data entry structure
	#Person entries personal data to back end
		#Generate individual risk factor value for individual
			#Positve or negative
			#Symptoms
			#Mask/No Mask
			#average contact range
		#Generate location history for person
			#logged manually using Google form format (Could be generated from opted in GPS data)
	#Person wants to cross check their data
		#Algorithm compares their data with that of the stored data
		#returns a risk factor based on the location data of people with a risk value

#Back end Data structure
	#Hierarchical HashMap strucure
		#State
			#Zip/City
				#Generated Location Nodes
					#Day Objects
						#15 Min time blocks within each day Object
	#Location Nodes are generated when needed based on data entered
	#Each 15 Min Time block is going to have a risk value generated by the individual risk value of the people present within that 15 minute block

#Translate Back-End into Heat Map
	#Iterate over all non-empty locaiton nodes and assign them RGB value based on risk value over specific time range



#Data Relay
	#Website Form - Backend Database running moodel
	#MySQL for queries
#Hold days in a queue so we can pop off the last added day and add a new day
#Use a HashTable

